# Generated by Django 4.0.5 on 2022-07-12 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_alter_review_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='ticket',
            field=models.ForeignKey(default=15, on_delete=django.db.models.deletion.CASCADE, to='review.ticket'),
            preserve_default=False,
        ),
    ]
